// <auto-generated />
using FrogoYou.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrogoYou.Migrations
{
    [DbContext(typeof(StoreDetailContext))]
    [Migration("20190913015641_ItemWantedPrice")]
    partial class ItemWantedPrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FrogoYou.Model.ItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemCurrentPrice");

                    b.Property<string>("ItemSalesPrice");

                    b.Property<string>("ItemStore");

                    b.Property<string>("ItemUrl");

                    b.Property<string>("ItemWantedPrice");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
